import { v4 as uuid } from 'uuid'
import { Constants } from './constants.js'

/**
 * Function to dynamically generate the filename for 
 * Multer that will get created at the path generated by destination()
 * @param {Request} req - Express.js request
 * @param {File} file - Multer file from upload
 * @param {Function} cb - Callback to Multer
 *  * @returns {String} - filename
 */
export const filename = (req, file, cb) => {
    cb(null, `${uuid()}${file.originalname.slice(file.originalname.lastIndexOf('.'))}`)
}

/**
 * Function to dynamically generate the destination path for 
 * images  uploaded with Multer 
* @param {Request} req - Express.js request
 * @param {File} file - Multer file from upload
 * @param {Function} cb - Callback to Multer
 * @returns {String} - destination path
 */
export const destination = (req, file, cb) => {
    cb(null, Constants.IMAGE_UPLOAD_PATH)
}